[C++23] Fix unique_ptr issue for incomplete types
C++23 changed unique_ptr to a constexpr so you need the type to be
completely defined before you pass it to unique_ptr. In this case, the
classes are not completely defined when their unique_ptr is defined. We
fix this by removing inline and defining the static variable in the
cpp/cc file with a nullptr.

Error:
prebuilts/clang/host/linux-x86/clang-r584948/include/c++/v1/__memory/unique_ptr.h:75:19:
error: invalid application of 'sizeof' to an incomplete type
'bluetooth_hal::transport::TransportInterface'
   75 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete
type");
prebuilts/clang/host/linux-x86/clang-r584948/include/c++/v1/__memory/unique_ptr.h:75:19:
error: invalid application of 'sizeof' to an incomplete type
'bluetooth_hal::bqr::BqrHandler'
   75 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete
type");
prebuilts/clang/host/linux-x86/clang-r584948/include/c++/v1/__memory/unique_ptr.h:75:19:
error: invalid application of 'sizeof' to an incomplete type
'bluetooth_hal::debug::BluetoothActivities'
   75 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete
type");
prebuilts/clang/host/linux-x86/clang-r584948/include/c++/v1/__memory/unique_ptr.h:75:19:
error: invalid application of 'sizeof' to an incomplete type
'bluetooth_hal::thread::ThreadHandler'
   75 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete
type");

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libbluetooth_hal
Test: m bluetooth_hal_bqr_test bluetooth_hal_bluetooth_activities_test
bluetooth_hal_transport_interface_test bluetooth_hal_thread_handler_test

Change-Id: I2b5f41f2d8110261655d62b9d515c0f9e83d9ad9