Add missing headers for C++23
Add headers to resolve C++23 build errors because C++23 removed
transitive includes so you have to add the headers directly.

Errors:
hardware/interfaces/graphics/composer/aidl/libhwc_aidl_test/GraphicsComposerCallback.cpp:240:21:
error: no member named 'any_of' in namespace 'std'
  240 |         return std::any_of(mHdcpLevelChangedDisplays.begin(),
mHdcpLevelChangedDisplays.end(),

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libhwc_aidl_test
Change-Id: I947caddce1563bfe45c548da792dd0e6da8d3a87